# These ara the commands we want the client to see.
# When you type / <tab> it will show these commands.
commands:
  - command1
  - command2

# This allows you to disable command execution if they are not on the list.
# For example, someone can type a command that is not on the list above and it will still execute.
# Set this to true so that does not happen.
actually-block-command-execution: true

# If you block commands that are not on the list, show them this message.
# Ideally it should be "unknown command" but you can do whatever.
invalid-command-message: "Unknown command. Type \"/help\" for help."