# Set which groups of players can see and do what commands.
# These groups are NOT the same from your permission plugin, they are separate.
# To assign a group these commands, you would give them tabcompleter.group.GROUPNAME (replace GROUPNAME with the name down below)
# If a player/group does not any permissions for a certain group on the list, it will use the default commands.
# You can add more groups, the ones that are default can be changed.

# Inherit let's you add commands from another group. For example: default -> vip -> admin. You would set admin to inherit vip, and vip to inherit default.
#
# Make sure to do /tcreload after changing this file to update in game.

# See -> https://github.com/hyperdefined/TabCompleter/wiki/Configuration
groups:
  admin:
    inherit: default
    commands:
      - helpbutadmin
  default:
    inherit: false
    commands:
      - help

# This allows you to disable command execution if they are not on the list.
# For example, someone can type a command that is not on the list above and it will still execute.
# Set this to true so that does not happen.
actually-block-command-execution: true

# If you block commands that are not on the list, show them this message.
# Ideally it should be "unknown command" but you can do whatever.
invalid-command-message: "Unknown command. Type \"/help\" for help."

config-version: 1