# Set which groups of players can see and do what commands.
# These groups will use the same name as your permission plugin! Make sure they match.
# Put each base command on a line.
# Default must be present.
# See -> https://github.com/hyperdefined/TabCompleter/wiki/Configuration
groups:
  admin:
    commands:
      - somevipcommand
      - help
      - plugins
  vip:
    commands:
      - somevipcommand
      - help
  default:
    commands:
      - help

# This allows you to disable command execution if they are not on the list.
# For example, someone can type a command that is not on the list above, and it will still execute.
# Set this to true so that does not happen.
actually-block-command-execution: true

# If you block commands that are not on the list, show them this message.
# Ideally it should be "unknown command" but you can do whatever.
invalid-command-message: "Unknown command. Type \"/help\" for help."

config-version: 2